language: ruby
rvm:
  - 2.4.1
before_install: gem install bundler -v 1.15.4

services:
  - postgresql
  
before_script:
  - psql -c 'create database taskmanager_test;' -U postgres
  - psql -c 'ALTER DATABASE taskmanager_test OWNER TO petr;' -U postgres

env:
  - TESTFOLDER=./
script: 
  - bundle exec rake -t 
  - bundle exec rubocop test